// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {"schemas":{"CaptchaResponse":{"properties":{"captcha_id":{"type":"string"},"captcha_length":{"type":"integer"},"pic_path":{"type":"string"}},"type":"object"},"LoginRequest":{"properties":{"captcha":{"type":"string"},"captcha_id":{"type":"string"},"password":{"maxLength":16,"minLength":6,"type":"string"},"username":{"maxLength":8,"minLength":4,"type":"string"}},"required":["captcha","captcha_id","password","username"],"type":"object"},"TokenResponse":{"properties":{"access_token":{"type":"string"},"expires_in":{"type":"integer"},"refresh_token":{"type":"string"},"token_type":{"type":"string"}},"type":"object"}}},
    "info": {"description":"{{escape .Description}}","title":"{{.Title}}","version":"{{.Version}}"},
    "externalDocs": {"description":"","url":""},
    "paths": {"/captcha":{"get":{"description":"获取成功后将验证码ID和图片路径返回","operationId":"get_captcha","requestBody":{"content":{"application/json":{"schema":{"type":"object"}}}},"responses":{"200":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/CaptchaResponse"}}},"description":"验证码"},"400":{"content":{"application/json":{"schema":{"type":"string"}}},"description":"验证码获取失败"}},"summary":"获取验证码","tags":["captcha"]}},"/login":{"post":{"description":"使用用户名和密码登录","operationId":"login","requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/LoginRequest"}}},"description":"登录请求","required":true},"responses":{"200":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/TokenResponse"}}},"description":"登录成功"},"400":{"content":{"application/json":{"schema":{"type":"string"}}},"description":"登录失败"}},"summary":"登录","tags":["auth"]}},"/logout":{"get":{"description":"退出登录","operationId":"logout","requestBody":{"content":{"application/json":{"schema":{"type":"object"}}}},"responses":{"204":{"content":{"application/json":{}},"description":"登出成功"},"400":{"content":{"application/json":{"schema":{"type":"string"}}},"description":"登出失败"},"401":{"content":{"application/json":{"schema":{"type":"string"}}},"description":"未授权"}},"security":[{"bearerauth":[]}],"summary":"登出","tags":["auth"]}},"/refresh_token":{"get":{"description":"使用refresh_token刷新access_token","operationId":"refresh_token","parameters":[{"description":"刷新令牌","in":"query","name":"refresh_token","required":true,"schema":{"type":"string"}}],"requestBody":{"content":{"application/json":{"schema":{"type":"object"}}}},"responses":{"200":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/TokenResponse"}}},"description":"刷新令牌成功"},"400":{"content":{"application/json":{"schema":{"type":"string"}}},"description":"刷新令牌失败"}},"security":[{"bearerauth":[]}],"summary":"刷新令牌","tags":["auth"]}}},
    "openapi": "3.1.0",
    "servers": [
        {"url":"127.0.0.1:6020/"}
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.1.0",
	Title:            "API接口文档",
	Description:      "API接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
