# 授权
auth:
  domain: http://localhost:6020
  access_secret: access_secret
  access_expire_time: 2h
  refresh_secret: refresh_secret
  refresh_expire_time: 7d

# 系统
system:
  host: 127.0.0.1
  port: 6020

# 日志
logger:
  level: "warn"
  directory: "logs"
  max_size: 10240
  max_backups: 30
  max_age: 7
  compress: true

# 数据库
database:
  host: 127.0.0.1
  port: 5432
  database: echo-admin
  username: admin
  password: admin2025
  pool:
    max_connections: 100
    min_connections: 10
    max_idle_time: 300
    connection_timeout: 5

# redis
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0
  pool:
    max_connections: 50
    min_idle_connections: 10
    max_idle_time: 300
  timeout:
    connect: 5
    read: 3
    write: 3