/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authEmailSignInRouteImport } from './routes/(auth)/email-sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedApiIndexRouteImport } from './routes/_authenticated/api/index'
import { Route as AuthenticatedMenuIndexRouteImport } from './routes/_authenticated/menu/index'
import { Route as AuthenticatedOperationLogIndexRouteImport } from './routes/_authenticated/operation-log/index'
import { Route as AuthenticatedRoleIndexRouteImport } from './routes/_authenticated/role/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsEmailRouteImport } from './routes/_authenticated/settings/email'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/_authenticated/settings/password'
import { Route as AuthenticatedSystemInfoIndexRouteImport } from './routes/_authenticated/system-info/index'
import { Route as AuthenticatedTaskIndexRouteImport } from './routes/_authenticated/task/index'
import { Route as AuthenticatedTenantIndexRouteImport } from './routes/_authenticated/tenant/index'
import { Route as AuthenticatedTokenIndexRouteImport } from './routes/_authenticated/token/index'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authEmailSignInRoute = authEmailSignInRouteImport.update({
  id: '/(auth)/email-sign-in',
  path: '/email-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiIndexRoute = AuthenticatedApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuIndexRoute = AuthenticatedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationLogIndexRoute =
  AuthenticatedOperationLogIndexRouteImport.update({
    id: '/operation-log/',
    path: '/operation-log/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleIndexRoute = AuthenticatedRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsEmailRoute =
  AuthenticatedSettingsEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSystemInfoIndexRoute =
  AuthenticatedSystemInfoIndexRouteImport.update({
    id: '/system-info/',
    path: '/system-info/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaskIndexRoute = AuthenticatedTaskIndexRouteImport.update({
  id: '/task/',
  path: '/task/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantIndexRoute =
  AuthenticatedTenantIndexRouteImport.update({
    id: '/tenant/',
    path: '/tenant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTokenIndexRoute = AuthenticatedTokenIndexRouteImport.update({
  id: '/token/',
  path: '/token/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/email-sign-in': typeof authEmailSignInRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/api/': typeof AuthenticatedApiIndexRoute
  '/menu/': typeof AuthenticatedMenuIndexRoute
  '/operation-log/': typeof AuthenticatedOperationLogIndexRoute
  '/role/': typeof AuthenticatedRoleIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/system-info/': typeof AuthenticatedSystemInfoIndexRoute
  '/task/': typeof AuthenticatedTaskIndexRoute
  '/tenant/': typeof AuthenticatedTenantIndexRoute
  '/token/': typeof AuthenticatedTokenIndexRoute
  '/user/': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesByTo {
  '/email-sign-in': typeof authEmailSignInRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/api': typeof AuthenticatedApiIndexRoute
  '/menu': typeof AuthenticatedMenuIndexRoute
  '/operation-log': typeof AuthenticatedOperationLogIndexRoute
  '/role': typeof AuthenticatedRoleIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/system-info': typeof AuthenticatedSystemInfoIndexRoute
  '/task': typeof AuthenticatedTaskIndexRoute
  '/tenant': typeof AuthenticatedTenantIndexRoute
  '/token': typeof AuthenticatedTokenIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/email-sign-in': typeof authEmailSignInRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/_authenticated/api/': typeof AuthenticatedApiIndexRoute
  '/_authenticated/menu/': typeof AuthenticatedMenuIndexRoute
  '/_authenticated/operation-log/': typeof AuthenticatedOperationLogIndexRoute
  '/_authenticated/role/': typeof AuthenticatedRoleIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/system-info/': typeof AuthenticatedSystemInfoIndexRoute
  '/_authenticated/task/': typeof AuthenticatedTaskIndexRoute
  '/_authenticated/tenant/': typeof AuthenticatedTenantIndexRoute
  '/_authenticated/token/': typeof AuthenticatedTokenIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/email-sign-in'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/email'
    | '/settings/notifications'
    | '/settings/password'
    | '/api/'
    | '/menu/'
    | '/operation-log/'
    | '/role/'
    | '/settings/'
    | '/system-info/'
    | '/task/'
    | '/tenant/'
    | '/token/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/email-sign-in'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/email'
    | '/settings/notifications'
    | '/settings/password'
    | '/api'
    | '/menu'
    | '/operation-log'
    | '/role'
    | '/settings'
    | '/system-info'
    | '/task'
    | '/tenant'
    | '/token'
    | '/user'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/email-sign-in'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/email'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/password'
    | '/_authenticated/api/'
    | '/_authenticated/menu/'
    | '/_authenticated/operation-log/'
    | '/_authenticated/role/'
    | '/_authenticated/settings/'
    | '/_authenticated/system-info/'
    | '/_authenticated/task/'
    | '/_authenticated/tenant/'
    | '/_authenticated/token/'
    | '/_authenticated/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authEmailSignInRoute: typeof authEmailSignInRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/email-sign-in': {
      id: '/(auth)/email-sign-in'
      path: '/email-sign-in'
      fullPath: '/email-sign-in'
      preLoaderRoute: typeof authEmailSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api/': {
      id: '/_authenticated/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof AuthenticatedApiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/': {
      id: '/_authenticated/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AuthenticatedMenuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation-log/': {
      id: '/_authenticated/operation-log/'
      path: '/operation-log'
      fullPath: '/operation-log/'
      preLoaderRoute: typeof AuthenticatedOperationLogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role/': {
      id: '/_authenticated/role/'
      path: '/role'
      fullPath: '/role/'
      preLoaderRoute: typeof AuthenticatedRoleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/email': {
      id: '/_authenticated/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AuthenticatedSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/password': {
      id: '/_authenticated/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/system-info/': {
      id: '/_authenticated/system-info/'
      path: '/system-info'
      fullPath: '/system-info/'
      preLoaderRoute: typeof AuthenticatedSystemInfoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task/': {
      id: '/_authenticated/task/'
      path: '/task'
      fullPath: '/task/'
      preLoaderRoute: typeof AuthenticatedTaskIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant/': {
      id: '/_authenticated/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof AuthenticatedTenantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/token/': {
      id: '/_authenticated/token/'
      path: '/token'
      fullPath: '/token/'
      preLoaderRoute: typeof AuthenticatedTokenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsEmailRoute: typeof AuthenticatedSettingsEmailRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsEmailRoute: AuthenticatedSettingsEmailRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApiIndexRoute: typeof AuthenticatedApiIndexRoute
  AuthenticatedMenuIndexRoute: typeof AuthenticatedMenuIndexRoute
  AuthenticatedOperationLogIndexRoute: typeof AuthenticatedOperationLogIndexRoute
  AuthenticatedRoleIndexRoute: typeof AuthenticatedRoleIndexRoute
  AuthenticatedSystemInfoIndexRoute: typeof AuthenticatedSystemInfoIndexRoute
  AuthenticatedTaskIndexRoute: typeof AuthenticatedTaskIndexRoute
  AuthenticatedTenantIndexRoute: typeof AuthenticatedTenantIndexRoute
  AuthenticatedTokenIndexRoute: typeof AuthenticatedTokenIndexRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApiIndexRoute: AuthenticatedApiIndexRoute,
  AuthenticatedMenuIndexRoute: AuthenticatedMenuIndexRoute,
  AuthenticatedOperationLogIndexRoute: AuthenticatedOperationLogIndexRoute,
  AuthenticatedRoleIndexRoute: AuthenticatedRoleIndexRoute,
  AuthenticatedSystemInfoIndexRoute: AuthenticatedSystemInfoIndexRoute,
  AuthenticatedTaskIndexRoute: AuthenticatedTaskIndexRoute,
  AuthenticatedTenantIndexRoute: AuthenticatedTenantIndexRoute,
  AuthenticatedTokenIndexRoute: AuthenticatedTokenIndexRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authEmailSignInRoute: authEmailSignInRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
